var HandshakeMessage = require('./handshake'),
    SayMessage = require('./say'),
    WhisperMessage = require('./whisper'),
    MoveMessage = require('./move'),
    RoomMsgMessage = require('./room_msg'),
    SetFaceMessage = require('./set_face'),
    SetColorMessage = require('./set_color'),
    SetSimpleAvatarMessage = require('./set_simple_avatar'),
    SetVideoAvatarMessage = require('./set_video_avatar'),
    NakedMessage = require('./naked'),
    DisconnectMessage = require('./disconnect'),
    YouTubeLoadMessage = require('./youtube_load'),
    YouTubePlayMessage = require('./youtube_play'),
    YouTubePauseMessage = require('./youtube_pause'),
    YouTubeStopMessage = require('./youtube_stop'),
    YouTubeSeekMessage = require('./youtube_seek'),
    YouTubeUnlockMessage = require('./youtube_unlock');

module.exports = {
    "say": SayMessage,
    "whisper": WhisperMessage,
    "handshake": HandshakeMessage,
    "move": MoveMessage,
    "disconnect": DisconnectMessage,
    "room_msg": RoomMsgMessage,
    "set_face": SetFaceMessage,
    "set_color": SetColorMessage,
    "set_simple_avatar": SetSimpleAvatarMessage,
    "set_video_avatar": SetVideoAvatarMessage,
    "naked": NakedMessage,
    "youtube_load": YouTubeLoadMessage,
    "youtube_play": YouTubePlayMessage,
    "youtube_pause": YouTubePauseMessage,
    "youtube_stop": YouTubeStopMessage,
    "youtube_seek": YouTubeSeekMessage,
    "youtube_unlock": YouTubeUnlockMessage
};